name: Download, Encode, and Upload

on:
  workflow_dispatch:
    inputs:
      input_file:
        description: "Input file name"
        required: true
      preset:
        description: "Preset to use when encoding"
        required: true
        default: '1080p'
        type: choice
        options:
          - 1080p
          - 1080p-animation
          - 4k
          - 4k-animation
      crf:
        description: "CRF value to use when encoding"
        required: true
        default: '20'
        type: string

jobs:
  encode-file:
    runs-on: ubuntu-latest

    env:
      BUCKET_NAME: ${{ vars.BUCKET_NAME }}
      ENDPOINT_URL: ${{ vars.ENDPOINT_URL }}
      ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
      SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}

    steps:
      # Install AWS CLI at a specific version - 2.23.6 has issues uploading to R2
      - name: Remove existing AWS CLI (if needed)
        run: |
          sudo rm -rf /usr/local/aws-cli
          sudo rm -rf /usr/bin/aws
          sudo rm -rf /usr/bin/aws_completer

      - name: Install AWS CLI v2.22.24
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.22.24.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          rm -r awscliv2.zip aws
          aws --version  # Verify installation

      - name: Configure AWS CLI
        run: |
          aws --version
          aws configure set aws_access_key_id $ACCESS_KEY_ID
          aws configure set aws_secret_access_key $SECRET_ACCESS_KEY
          aws configure set default.region auto
          aws configure set default.s3.endpoint $ENDPOINT_URL

      - name: Download File
        run: |
          aws s3 cp s3://$BUCKET_NAME/${{ github.event.inputs.input_file }} ./ --endpoint-url $ENDPOINT_URL

      - name: Encode File with Docker image
        run: |
          docker run --rm -v "$(pwd)":/data davidmatthews/handbrake-cli ${{ github.event.inputs.input_file }} ${{ github.event.inputs.preset }} ${{ github.event.inputs.crf }}

      - name: Upload Encoded File
        run: |
          # Remove original file before uploading
          rm -f ${{ github.event.inputs.input_file }}
          aws s3 cp ./ s3://$BUCKET_NAME/ --recursive --endpoint-url $ENDPOINT_URL